### ISSUE TITLE
Rename ingestor_cloudfoundry-firehose job to ingestor_cloudfoundry_firehose

### ISSUE THREAD

**Issue by longnguyen11288** [logsearch/logsearch-for-cloudfoundry#36]
Keep things consistent and don't be butt ugly

**Comment by shinji62** [comment]
lol

**Comment by mrdavidlaing** [comment]
I named it like this because I consider `cloudfoundry-firehose` a single concept.

I'm trying to say `ingestor` of type `cloudfoundry-firehose`.

In my mind this is consistent:
* `ingestor_syslog` => `ingestor` of type `syslog`
* `ingestor_relp` => `ingestor` of type `relp`

Sorry for asthetic offence caused.  If it makes you feel better, consider this job's name as the ugly one that shows how beautiful the other names are :wink:
